server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluation?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 105036
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true

mybatis:
  type-aliases-package: com.watermelon.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    # 在控制台显示 sql 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#配置日志输出等级以及日志文件输出位置
#logging:
#  level:
#    root: info
#    com.watermleon: info
#  file:
#    #生产环境下的log路径
#    name: /itcast/log/project.log
#    #开发环境下的log路径
#    #name: log/project.log

#swagger接口文档开关
switch-swagger-up: true
